# Generated by Django 5.1 on 2024-08-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('surname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('create_login', models.CharField(max_length=150, verbose_name='Придумайте логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('repet_password', models.CharField(max_length=255, verbose_name='Повторите пароль')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Почта')),
            ],
        ),
    ]
